### PR TITLE
string url to URL interface

### PR DESCRIPTION
**Pull request by ethicnology**
Moving from a string url to the [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) interface
Add from code example to README.md

### CODE REVIEW

**Comment by timonson** [comment]
Thanks!

**Comment by timonson** [comment]
@ethicnology I modified your changes a little bit afterwards. Let me please know if this causes difficulties.

**Comment by ethicnology** [comment]
Nice, works fine !

**Comment by ethicnology** [comment]
@timonson I added your library in Bitcoin wiki https://en.bitcoin.it/wiki/API_reference_(JSON-RPC)#Deno

**Comment by timonson** [comment]
Hi @ethicnology I hope you are doing great! Would you mind editing the Bitcoin wiki because I had to change the name from `gentleRpc` to `gentle_rpc`. Otherwise I could not have implemented the webhooks for deno's third library modules.
You would also have to change the links to this repo there. Thank you very much!

**Comment by ethicnology** [comment]
@timonson done ;)

**Pull request merged**
